### ISSUE TITLE
`viewCount` is always 0 & Missing token

### ISSUE THREAD

**Issue by chocobearxo** [TheHellTower/Reddit-Meme-Fetcher#1]
I've now gotten results with comments and votes being positive numbers, with `viewCount` still being `0`, kinda weird.
Also, in `headers` a token is required:
```js
headers: {
    "User-Agent": this.#REPO,
    Authorization: "TOKEN" // You get one from https://www.reddit.com/prefs/apps
}
```

Other than that, really great library! :D

**Comment by TheHellTower** [comment]
> I've now gotten results with comments and votes being positive numbers, with `viewCount` still being `0`, kinda weird. Also, in `headers` a token is required:
> 
> ```js
> headers: {
>     "User-Agent": this.#REPO,
>     Authorization: "TOKEN" // You get one from https://www.reddit.com/prefs/apps
> }
> ```
> 
> Other than that, really great library! :D

Hello, I might need to remove `viewCount` because it's always null in the response..
![Code_1DA71GdEFZ](https://github.com/TheHellTower/Reddit-Meme-Fetcher/assets/119943599/5cff01ff-8471-4e94-b9eb-b711188879c9)

Also modify the response a bit to add a few missing elements for stats purposes mainly such as the number of comments or other if existing.

I didn't know we know need a `Authorization` to reach it ? I mean, I still get the response without needing it ? I'm not sure if it just affect some area, could you tell me more ?

Thank you but it's very basic anyway and you can contribute if you want to ! :)

Best Regards,
TheHelllTower.

**Comment by TheHellTower** [comment]
After some time testing to access your link:
![opera_TrySqq9q2J](https://github.com/TheHellTower/Reddit-Meme-Fetcher/assets/119943599/ca346633-6150-489a-89b0-6b9cb7da96fc)

**Comment by TheHellTower** [comment]
To reach this and get the info you don't need a `TOKEN` I believe you want to make a bot ? In this case yes you would need a `TOKEN` but not to fetch these data I believe.
Maybe I will add bot support soon.

**Comment by chocobearxo** [comment]
Hmm, I'm not sure what the issue is with `https://www.reddit.com/prefs/apps`.
regarding the token, I kept getting an error, not sure which it was, but I think it was a normal `FetchError` and after adding that token part, it worked. Again not sure, I just remember it working after adding a token. 



> To reach this and get the info you don't need a `TOKEN` I believe you want to make a bot ? In this case yes you would need a `TOKEN` but not to fetch these data I believe. Maybe I will add bot support soon.

And yes it's for a bot, but the token for the bot is all in order, it was a fetching error, something that was fixed by adding a token (or something else, I modified the library a tiny bit to my needs, so it might have been something else, not 100% sure) 😄

**Comment by chocobearxo** [comment]
I'll try to remove the token part and make a request on my test bot and then get back to you.

**Comment by TheHellTower** [comment]
> Hmm, I'm not sure what the issue is with `https://www.reddit.com/prefs/apps`. regarding the token, I kept getting an error, not sure which it was, but I think it was a normal `FetchError` and after adding that token part, it worked. Again not sure, I just remember it working after adding a token.
> 
> > To reach this and get the info you don't need a `TOKEN` I believe you want to make a bot ? In this case yes you would need a `TOKEN` but not to fetch these data I believe. Maybe I will add bot support soon.
> 
> And yes it's for a bot, but the token for the bot is all in order, it was a fetching error, something that was fixed by adding a token (or something else, I modified the library a tiny bit to my needs, so it might have been something else, not 100% sure) 😄

Well yeah try without and get back to me because I can reach these info with success everytime without any problem !

**Comment by chocobearxo** [comment]
> I'll try to remove the token part and make a request on my test bot and then get back to you.

Yeah it seems to work also without a token. It's currently 2am for me, so I might have confused it with something else. 🤷‍♀️

**Comment by TheHellTower** [comment]
> 

Maybe haha I suppose this issue is solved !:)

**Comment by chocobearxo** [comment]
Yup, other than the `viewCount` always being `0` part, but it seemed like that was completely out of your hands?

**Comment by TheHellTower** [comment]
> Yup, other than the `viewCount` always being `0` part, but it seemed like that was completely out of your hands?

Exactly like I showed on the screenshot it's out of my control !

I wish you a good day/night and open a issue again if you have any idea or problem ! :)
