### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by chocobearxo** [TheHellTower/Reddit-Meme-Fetcher#2]
I fairly often get this error without knowing the reason. It comes from `reddit-meme-fetcher\src\RedditMemesFetcher.js:43:135`.
I have no idea what the requests were by the way, it just pops up in my console from time to time.

**Comment by TheHellTower** [comment]
> I fairly often get this error without knowing the reason. It comes from `reddit-meme-fetcher\src\RedditMemesFetcher.js:43:135`. I have no idea what the requests were by the way, it just pops up in my console from time to time.

Hello,

There is not enough info.
How the filter is giving a error ? You only gave the line and char position but not the actual error.
Please show the actual error it might be useful.

Best Regards,
TheHellTower.

**Comment by TheHellTower** [comment]
> > > I fairly often get this error without knowing the reason. It comes from `reddit-meme-fetcher\src\RedditMemesFetcher.js:43:135`. I have no idea what the requests were by the way, it just pops up in my console from time to time.
> > 
> > 
> > Hello,
> > There is not enough info. How the filter is giving a error ? You only gave the line and char position but not the actual error. Please show the actual error it might be useful.
> > Best Regards, TheHellTower.
> 
> The actual error is in the title 😅 Althought I just tried updating which now means I'm on version 1.0.3 which seems to have fixed the problem!

Oh sorry I didn't see the title !
The 1.0.3 only change the result and one of the changes is `viewsCount` that got removed so I believe it was just a error you got once and it should be okay !
I will leave this issue open for the next 2 days so if you get this error again you can comment.

**Comment by TheHellTower** [comment]
> > > > > I fairly often get this error without knowing the reason. It comes from `reddit-meme-fetcher\src\RedditMemesFetcher.js:43:135`. I have no idea what the requests were by the way, it just pops up in my console from time to time.
> > > > 
> > > > 
> > > > Hello,
> > > > There is not enough info. How the filter is giving a error ? You only gave the line and char position but not the actual error. Please show the actual error it might be useful.
> > > > Best Regards, TheHellTower.
> > > 
> > > 
> > > The actual error is in the title 😅 Althought I just tried updating which now means I'm on version 1.0.3 which seems to have fixed the problem!
> > 
> > 
> > Oh sorry I didn't see the title ! The 1.0.3 only change the result and one of the changes is `viewsCount` that got removed so I believe it was just a error you got once and it should be okay ! I will leave this issue open for the next 2 days so if you get this error again you can comment.
> 
> It was an error I eventually got from EVERY request on `v1.0.2`, not just once. But somehow `v1.0.3` doesn't. I had modified the library a bit to my needs, but I did as well after updating to `v1.0.3` and it works as well after that, so I don't _think_ it had anything to do with that, not sure though. 🤷‍♀️

No problem ! I close your issue as solved then !

**Comment by TheHellTower** [comment]
Fixes #3
