### ISSUE TITLE
Issue from #2 occurs again, often.

### ISSUE THREAD

**Issue by chocobearxo** [TheHellTower/Reddit-Meme-Fetcher#3]
The issue (#2) is happening again. :/

![img](https://i.gyazo.com/bd3fe742f1358e9e22cfda5f390b8fba.png)

**Comment by TheHellTower** [comment]
> The issue (#2) is happening again. :/
> 
> ![img](https://camo.githubusercontent.com/652d28e0dbc7638e13a899a7325eccaa79ec4cc0b07e712c20fc6792bf5e8b2f/68747470733a2f2f692e6779617a6f2e636f6d2f62643366653734326631333538653965323263666461356633393062386662612e706e67)

Hey,

The line `41` doesn't even contain `135` chars, did you modify the package ?
Anyway since I have no clue why it does that I believe MAYBE there is a ratelimit.
Could you please in your project modify the module code [here](https://github.com/TheHellTower/Reddit-Meme-Fetcher/blob/main/src/RedditMemesFetcher.js#L43) and add a `console.log` of `jsonData` and post a screenshot when this error occurs ?
Would looks like that:
```js
//...
console.log(jsonData);
const allowed = ageGate ? jsonData["data"]["children"].filter((post) => !post.data.over_18) : jsonData["data"]["children"];
//...
```

Best Regards,
TheHellTower.

**Comment by TheHellTower** [comment]
![Code_1tRnWIeA1K](https://github.com/TheHellTower/Reddit-Meme-Fetcher/assets/119943599/3be03ab9-8e03-4691-aead-9b5147b17ffd)
So it's a `ratelimit` problem. I implemented a workaround for it.
![Code_vSgEyahwOi](https://github.com/TheHellTower/Reddit-Meme-Fetcher/assets/119943599/edf347fe-eb8a-449e-9d18-d22d2de97e68)
So when you are rate limited you will get the error response instead of this error you got.

**Comment by TheHellTower** [comment]
You can now update and tell me if it solve your problem.

**Comment by TheHellTower** [comment]
I found a workaround but it might be a bit tricky since I'm suing `https` as module, but it's possible to add proxy support. Even with `fetch` I believe.

**Comment by chocobearxo** [comment]
> > The issue (#2) is happening again. :/
> > ![img](https://camo.githubusercontent.com/652d28e0dbc7638e13a899a7325eccaa79ec4cc0b07e712c20fc6792bf5e8b2f/68747470733a2f2f692e6779617a6f2e636f6d2f62643366653734326631333538653965323263666461356633393062386662612e706e67)
> 
> Hey,
> 
> The line `41` doesn't even contain `135` chars, did you modify the package ? Anyway since I have no clue why it does that I believe MAYBE there is a ratelimit. Could you please in your project modify the module code [here](https://github.com/TheHellTower/Reddit-Meme-Fetcher/blob/main/src/RedditMemesFetcher.js#L43) and add a `console.log` of `jsonData` and post a screenshot when this error occurs ? Would looks like that:
> 
> ```js
> //...
> console.log(jsonData);
> const allowed = ageGate ? jsonData["data"]["children"].filter((post) => !post.data.over_18) : jsonData["data"]["children"];
> //...
> ```
> 
> Best Regards, TheHellTower.

Sure, here:

```js
const https = require("https");

module.exports = class RedditMemesFetcher {
    #API = `443:www.reddit.com:/r/{{Sub}}.json?sort=top&t=week`;
    #REPO = "https://github.com/TheHellTower/Reddit-Meme-Fetcher"
    #Format = ""; //ToDO: Add Format Support

    /**
     * @constructor
     * @param {string} Format json || description => (default: json = full data on the post.) (not implemented yet)
     */
    constructor(Format = "json") {
        this.#Format = Format;
    }

    /**
     * Get A Random Meme
     * @param {true} ageGate true || false => (default: true = filter +18 content)
     * @returns {Promise<boolean>}
     */
    getRandomMeme(subreddit, ageGate = true) {
        return new Promise(async (resolve, reject) => {
            var splitted = this.#API.split(':');
            var req = https.request({
                host: splitted[1],
                port: splitted[0],
                path: splitted[2].replace("{{Sub}}", subreddit),
                method: "GET",
                headers: {
                    "User-Agent": this.#REPO
                }
            }, res => {
                var jsonData = "";

                res.on("data", body => {
                    jsonData += body.toString();
                })
                    .on("error", e => reject(e))
                    .on("end", x => {
                        jsonData = JSON.parse(jsonData);
                        const allowed = ageGate ? jsonData["data"]["children"].filter((post) => !post.data.over_18) : jsonData["data"]["children"];
                        if (!allowed.length) return reject({ error: true, message: `There are no fresh \`${subreddit}\` memes try again !` });
                        const randomMeme = allowed[Math.floor(Math.random() * allowed.length)];
                        return resolve({
                            error: false,
                            data: {
                                sub: {
                                    name: subreddit,
                                    subscribers: randomMeme.data.subreddit_subscribers
                                },
                                author: {
                                    name: randomMeme.data.author,
                                    fullName: randomMeme.data.author_fullname,
                                    flairText: randomMeme.data.author_flair_text,
                                    isBlocked: randomMeme.data.author_is_blocked,
                                    isPremium: randomMeme.data.author_premium
                                },
                                post: {
                                    comments: randomMeme.data.num_comments,
                                    edited: randomMeme.data.edited,
                                    imageURL: {
                                        url: randomMeme.data.url,
                                        urlOverriden: randomMeme.data.url_overridden_by_dest
                                    },
                                    score: randomMeme.data.score,
                                    thumbnail: {
                                        url: randomMeme.data.thumbnail,
                                        height: randomMeme.data.thumbnail_height,
                                        width: randomMeme.data.thumbnail_width,
                                    },
                                    title: randomMeme.data.title,
                                    votes: {
                                        up: randomMeme.data.ups,
                                        upRatio: randomMeme.data.upvote_ratio,
                                        Down: randomMeme.data.downs
                                    },
                                    permaLink: `https://${splitted[1]}${randomMeme.data.permalink}`,
                                    extra: {
                                        archived: randomMeme.data.archived,
                                        created: randomMeme.data.created,
                                        createdAsDate: new Date(randomMeme.data.created * 1000),
                                        isVideo: randomMeme.data.is_video,
                                        media_only: randomMeme.data.media_only,
                                        over18: randomMeme.data.over_18,
                                        pinned: randomMeme.data.pinned,
                                        spoiler: randomMeme.data.spoiler
                                    }
                                }
                            }
                        });
                    });
            });
            req.write(this.#REPO);
            req.end();
        });
    }
}
```

**Comment by chocobearxo** [comment]
I updated. I'll get back to you if another error comes along then, then close this issue in a couple of days if no error comes along.

**Comment by TheHellTower** [comment]
> I updated. I'll get back to you if another error comes along then, then close this issue in a couple of days if no error comes along.

You should not get any other error than a 429 which is a normal error it's made to avoid abuses.

**Comment by chocobearxo** [comment]
```js
const fetcher = new RedditMemesFetcher();
let result = await fetcher.getRandomMeme(random, false)
let data = result.data
let post = data.post
let image = post.imageURL.url.replace('.gifv', '.gif')
```

I get `TypeError: Cannot read properties of undefined (reading 'imageURL')` very often now.

**Comment by TheHellTower** [comment]
> ```js
> const fetcher = new RedditMemesFetcher();
> let result = await fetcher.getRandomMeme(random, false)
> let data = result.data
> let post = data.post
> let image = post.imageURL.url.replace('.gifv', '.gif')
> ```
> 
> I get `TypeError: Cannot read properties of undefined (reading 'imageURL')` very often now. So `error` probably returned `true`. They are NSFW subreddits btw.

console.log data

**Comment by chocobearxo** [comment]
> > ```js
> > const fetcher = new RedditMemesFetcher();
> > let result = await fetcher.getRandomMeme(random, false)
> > let data = result.data
> > let post = data.post
> > let image = post.imageURL.url.replace('.gifv', '.gif')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I get `TypeError: Cannot read properties of undefined (reading 'imageURL')` very often now. So `error` probably returned `true`. They are NSFW subreddits btw.
> 
> console.log data and if it looks okay console.log post

If I try to console log anything here, the console is gonna get massively spammed. I can't really do that :(

**Comment by TheHellTower** [comment]
> > > ```js
> > > const fetcher = new RedditMemesFetcher();
> > > let result = await fetcher.getRandomMeme(random, false)
> > > let data = result.data
> > > let post = data.post
> > > let image = post.imageURL.url.replace('.gifv', '.gif')
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I get `TypeError: Cannot read properties of undefined (reading 'imageURL')` very often now. So `error` probably returned `true`. They are NSFW subreddits btw.
> > 
> > 
> > console.log data and if it looks okay console.log post
> 
> If I try to console log anything here, the console is gonna get massively spammed. I can't really do that :(

Then I can't do anything for you ? If you can't do this to diagnose the problem I can't solve it.

**Comment by chocobearxo** [comment]
I could try...catch it and only log if it catches an error. I'm just not sure where it comes from since I use the library in multiple features. I'll try to figure that part out if you just keep this issue open for me. :)

**Comment by TheHellTower** [comment]
> I could try...catch it and only log if it catches an error. I'm just not sure where it comes from since I use the library in multiple features. I'll try to figure that part out if you just keep this issue open for me. :)

I mean you are developer, I don't think I need to tell you when to use a catch, the error should tell you also where it's coming from..

**Comment by chocobearxo** [comment]
> > I could try...catch it and only log if it catches an error. I'm just not sure where it comes from since I use the library in multiple features. I'll try to figure that part out if you just keep this issue open for me. :)
> 
> I mean you are developer, I don't think I need to tell you when to use a catch, the error should tell you also where it's coming from..

And it says it comes from the library.. Which is what I showed to begin with

**Comment by TheHellTower** [comment]
> > > I could try...catch it and only log if it catches an error. I'm just not sure where it comes from since I use the library in multiple features. I'll try to figure that part out if you just keep this issue open for me. :)
> > 
> > 
> > I mean you are developer, I don't think I need to tell you when to use a catch, the error should tell you also where it's coming from..
> 
> And it says it comes from the library.. Which is what I showed to begin with

No, it says the place where you executed this too.
The code you provided above doesn't come from the library but was wrote in your end.

**Comment by TheHellTower** [comment]
Did you try to catch the error ?

**Comment by chocobearxo** [comment]
> Did you try to catch the error ?

I do kinda have an idea why it's happening. And if I'm right then I'm just f**king stupid... Let's see by tomorrow if it still happens, if not, then my mistake xD - if there's still an issue, I'll let you know too ofc.

**Comment by TheHellTower** [comment]
> > Did you try to catch the error ?
> 
> I do kinda have an idea why it's happening. And if I'm right then I'm just f**king stupid... Let's see by tomorrow if it still happens, if not, then my mistake xD - if there's still an issue, I'll let you know too ofc.

Well, asking a last time to be sure !
Did any problem happen ?

**Comment by chocobearxo** [comment]
> > > Did you try to catch the error ?
> > 
> > 
> > I do kinda have an idea why it's happening. And if I'm right then I'm just f**king stupid... Let's see by tomorrow if it still happens, if not, then my mistake xD - if there's still an issue, I'll let you know too ofc.
> 
> Well, asking a last time to be sure ! Did any problem happen ?

Nop, problem is solved now !
