### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by iced-queen** [TheHellTower/Reddit-Meme-Fetcher#4]
I am constantly geting the `SyntaxError: Unexpected token < in JSON at position 0` error from this line:
```js
jsonData = JSON.parse(jsonData);
```

**Comment by TheHellTower** [comment]
> I am constantly geting the `SyntaxError: Unexpected token < in JSON at position 0` error from this line:
> 
> ```js
> jsonData = JSON.parse(jsonData);
> ```

Could you edit the package to see what `jsonData` output before being re-assigned ? So before the line you sent !

**Comment by chocobearxo** [comment]
> > I am constantly geting the `SyntaxError: Unexpected token < in JSON at position 0` error from this line:
> > ```js
> > jsonData = JSON.parse(jsonData);
> > ```
> 
> Could you edit the package to see what `jsonData` output before being re-assigned ? So before the line you sent !

I don't mean this in a rude way, but can you not? 😅 I'm not really able to since I'm quite busy lately, I just noticed the error ^^

**Comment by TheHellTower** [comment]
> > > I am constantly geting the `SyntaxError: Unexpected token < in JSON at position 0` error from this line:
> > > ```js
> > > jsonData = JSON.parse(jsonData);
> > > ```
> > 
> > 
> > Could you edit the package to see what `jsonData` output before being re-assigned ? So before the line you sent !
> 
> I don't mean this in a rude way, but can you not? 😅 I'm not really able to since I'm quite busy lately, I just noticed the error ^^

I don't need this package and I believe you might be the only person really using it, like I said in an earlier issue if I remember correctly is, as a dev, if you are not willing to help and do some efforts(https://github.com/TheHellTower/Reddit-Meme-Fetcher/issues/3#issuecomment-1693510372), I will not be able to do much since I will not debug an error for a package no one need or use.. I have things to do too.

**Comment by chocobearxo** [comment]
> > > > I am constantly geting the `SyntaxError: Unexpected token < in JSON at position 0` error from this line:
> > > > ```js
> > > > jsonData = JSON.parse(jsonData);
> > > > ```
> > > 
> > > 
> > > Could you edit the package to see what `jsonData` output before being re-assigned ? So before the line you sent !
> > 
> > 
> > I don't mean this in a rude way, but can you not? 😅 I'm not really able to since I'm quite busy lately, I just noticed the error ^^
> 
> I don't need this package and I believe you might be the only person really using it, like I said in an earlier issue if I remember correctly is, as a dev, if you are not willing to help and do some efforts([#3 (comment)](https://github.com/TheHellTower/Reddit-Meme-Fetcher/issues/3#issuecomment-1693510372)), I will not be able to do much since I will not debug an error for a package no one need or use.. I have things to do too.

You're right. Found time. 🙂 

It seems to return a login screen.

```html
<!doctype html>
     <html>
  <head>
    <title>Blocked</title>
    <style>
      body {
          font: small verdana, arial, helvetica, sans-serif;
          width: 600px;
          margin: 0 auto;
      }

      h1 {
          height: 40px;
          background: transparent url(//www.redditstatic.com/reddit.com.header.png) no-repeat scroll top right;
      }
    </style>
  </head>
  <body>
    <h1>whoa there, pardner!</h1>

<p>Your request has been blocked due to a network policy.</p>

<p>Try logging in or creating an account <a href=https://www.reddit.com/login/>here</a> to get back to browsing.</p>

<p>If you're running a script or application, please register or sign in with your developer credentials <a href=https://www.reddit.com/wiki/api/>here</a>. Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string,
try changing back to default as that can sometimes result in a block.</p>

<p>You can read Reddit's Terms of Service <a href=https://www.reddit.com/wiki/api/>here</a>.</p>

<p>if you think that we've incorrectly blocked you or you would like to discuss
easier ways to get the data you want, please file a ticket <a href=https://support.reddithelp.com/hc/en-us/requests/new?ticket_form_id=21879292693140>here</a>.</p>

<p>when contacting us, please include your ip address which is: <strong>SECRET_STUFF_LOL</strong> and reddit account</p>
  </body>
</html>
```

**Comment by TheHellTower** [comment]
> > > > > I am constantly geting the `SyntaxError: Unexpected token < in JSON at position 0` error from this line:
> > > > > ```js
> > > > > jsonData = JSON.parse(jsonData);
> > > > > ```
> > > > 
> > > > 
> > > > Could you edit the package to see what `jsonData` output before being re-assigned ? So before the line you sent !
> > > 
> > > 
> > > I don't mean this in a rude way, but can you not? 😅 I'm not really able to since I'm quite busy lately, I just noticed the error ^^
> > 
> > 
> > I don't need this package and I believe you might be the only person really using it, like I said in an earlier issue if I remember correctly is, as a dev, if you are not willing to help and do some efforts([#3 (comment)](https://github.com/TheHellTower/Reddit-Meme-Fetcher/issues/3#issuecomment-1693510372)), I will not be able to do much since I will not debug an error for a package no one need or use.. I have things to do too.
> 
> You're right. Found time. 🙂
> 
> It seems to return a login screen.
> 
> ```
> <!doctype html>
>      <html>
>   <head>
>     <title>Blocked</title>
>     <style>
>       body {
>           font: small verdana, arial, helvetica, sans-serif;
>           width: 600px;
>           margin: 0 auto;
>       }
> 
>       h1 {
>           height: 40px;
>           background: transparent url(//www.redditstatic.com/reddit.com.header.png) no-repeat scroll top right;
>       }
>     </style>
>   </head>
>   <body>
>     <h1>whoa there, pardner!</h1>
> 
> <p>Your request has been blocked due to a network policy.</p>
> 
> <p>Try logging in or creating an account <a href=https://www.reddit.com/login/>here</a> to get back to browsing.</p>
> 
> <p>If you're running a script or application, please register or sign in with your developer credentials <a href=https://www.reddit.com/wiki/api/>here</a>. Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string,
> try changing back to default as that can sometimes result in a block.</p>
> 
> <p>You can read Reddit's Terms of Service <a href=https://www.reddit.com/wiki/api/>here</a>.</p>
> 
> <p>if you think that we've incorrectly blocked you or you would like to discuss
> easier ways to get the data you want, please file a ticket <a href=https://support.reddithelp.com/hc/en-us/requests/new?ticket_form_id=21879292693140>here</a>.</p>
> 
> <p>when contacting us, please include your ip address which is: <strong>SECRET_STUFF_LOL</strong> and reddit account</p>
>   </body>
> </html>
> ```
> 
> `console.log(jsonData)` before `JSON.parse(jsonData)`

Maybe ti finally require an account or it could detect it as an app request due to some missing info.

**Comment by TheHellTower** [comment]
> reddit-meme-fetcher@1.0.4 test
> node test/Main.js


```json

{
  sub: { name: 'HistoryMemes', subscribers: 8817227 },
  author: {
    name: 'Nakatsukasa',
    fullName: 't2_2h1aa2w1',
    flairText: null,
    isBlocked: false,
    isPremium: false
  },
  post: {
    comments: 138,
    edited: false,
    imageURL: {
      url: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg',
      urlOverriden: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg'
    },
    score: 10541,
    thumbnail: {
      url: 'https://b.thumbs.redditmedia.com/Hp9GNib0kUhQ8UjO9CrXboOSYwBXOfGMWXLsQNNZ5_U.jpg',
      height: 140,
      width: 140
    },
    title: 'Now make him enter a cage match with Plato',
    votes: { up: 10541, upRatio: 0.99, Down: 0 },
    permaLink: 'https://www.reddit.com/r/HistoryMemes/comments/18kzxs9/now_make_him_enter_a_cage_match_with_plato/',
    extra: {
      archived: false,
      created: 1702872913,
      createdAsDate: 2023-12-18T04:15:13.000Z,
      isVideo: false,
      media_only: false,
      over18: false,
      pinned: false,
      spoiler: false
    }
  }
}
```

There might be an issue on your end it's working correctly on mine..

**Comment by iced-queen** [comment]
> > reddit-meme-fetcher@1.0.4 test
> > node test/Main.js
> 
> ```js
> {
>   sub: { name: 'HistoryMemes', subscribers: 8817227 },
>   author: {
>     name: 'Nakatsukasa',
>     fullName: 't2_2h1aa2w1',
>     flairText: null,
>     isBlocked: false,
>     isPremium: false
>   },
>   post: {
>     comments: 138,
>     edited: false,
>     imageURL: {
>       url: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg',
>       urlOverriden: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg'
>     },
>     score: 10541,
>     thumbnail: {
>       url: 'https://b.thumbs.redditmedia.com/Hp9GNib0kUhQ8UjO9CrXboOSYwBXOfGMWXLsQNNZ5_U.jpg',
>       height: 140,
>       width: 140
>     },
>     title: 'Now make him enter a cage match with Plato',
>     votes: { up: 10541, upRatio: 0.99, Down: 0 },
>     permaLink: 'https://www.reddit.com/r/HistoryMemes/comments/18kzxs9/now_make_him_enter_a_cage_match_with_plato/',
>     extra: {
>       archived: false,
>       created: 1702872913,
>       createdAsDate: 2023-12-18T04:15:13.000Z,
>       isVideo: false,
>       media_only: false,
>       over18: false,
>       pinned: false,
>       spoiler: false
>     }
>   }
> }
> ```
> 
> There might be an issue on your end it's working correctly on mine..

I've modified the library a little, but I can't see where it would go wrong
```js
const https = require("https");

module.exports = class RedditMemesFetcher {
    #API = `443:www.reddit.com:/r/{{Sub}}.json?sort=top&t=week`;
    #REPO = "https://github.com/TheHellTower/Reddit-Meme-Fetcher"
    #Format = ""; //ToDO: Add Format Support

    /**
     * @constructor
     * @param {string} Format json || description => (default: json = full data on the post.) (not implemented yet)
     */
    constructor(Format = "json") {
        this.#Format = Format;
    }

    /**
     * Get A Random Meme
     * @param {true} ageGate true || false => (default: true = filter +18 content)
     * @returns {Promise<boolean>}
     */
    getRandomMeme(subreddit, ageGate = true) {
        return new Promise(async (resolve, reject) => {
            var splitted = this.#API.split(':');
            var req = https.request({
                host: splitted[1],
                port: splitted[0],
                path: splitted[2].replace("{{Sub}}", subreddit),
                method: "GET",
                headers: {
                    "User-Agent": this.#REPO
                }
            }, res => {
                var jsonData = "";

                res.on("data", body => {
                    jsonData += body.toString();
                })
                    .on("error", e => reject(e))
                    .on("end", x => {
                        jsonData = JSON.parse(jsonData);
                        if (jsonData.error) return resolve({ error: true, data: { code: jsonData.error, message: jsonData.message } });
                        const allowed = ageGate ? jsonData["data"]["children"].filter((post) => !post.data.over_18) : jsonData["data"]["children"];
                        if (!allowed.length) return reject({ error: true, message: `There are no fresh \`${subreddit}\` memes try again !` });
                        const randomMeme = allowed[Math.floor(Math.random() * allowed.length)];
                        return resolve({
                            error: false,
                            data: {
                                sub: {
                                    name: subreddit,
                                    subscribers: randomMeme.data.subreddit_subscribers
                                },
                                author: {
                                    name: randomMeme.data.author,
                                    fullName: randomMeme.data.author_fullname,
                                    flairText: randomMeme.data.author_flair_text,
                                    isBlocked: randomMeme.data.author_is_blocked,
                                    isPremium: randomMeme.data.author_premium
                                },
                                post: {
                                    comments: randomMeme.data.num_comments,
                                    edited: randomMeme.data.edited,
                                    imageURL: {
                                        url: randomMeme.data.url,
                                        urlOverriden: randomMeme.data.url_overridden_by_dest
                                    },
                                    score: randomMeme.data.score,
                                    thumbnail: {
                                        url: randomMeme.data.thumbnail,
                                        height: randomMeme.data.thumbnail_height,
                                        width: randomMeme.data.thumbnail_width,
                                    },
                                    title: randomMeme.data.title,
                                    votes: {
                                        up: randomMeme.data.ups,
                                        upRatio: randomMeme.data.upvote_ratio,
                                        Down: randomMeme.data.downs
                                    },
                                    permaLink: `https://${splitted[1]}${randomMeme.data.permalink}`,
                                    extra: {
                                        archived: randomMeme.data.archived,
                                        created: randomMeme.data.created,
                                        createdAsDate: new Date(randomMeme.data.created * 1000),
                                        isVideo: randomMeme.data.is_video,
                                        media_only: randomMeme.data.media_only,
                                        over18: randomMeme.data.over_18,
                                        pinned: randomMeme.data.pinned,
                                        spoiler: randomMeme.data.spoiler
                                    }
                                }
                            }
                        });
                    });
            });
            req.write(this.#REPO);
            req.end();
        });
    }
}
```

**Comment by TheHellTower** [comment]
> > > reddit-meme-fetcher@1.0.4 test
> > > node test/Main.js
> > 
> > 
> > ```js
> > {
> >   sub: { name: 'HistoryMemes', subscribers: 8817227 },
> >   author: {
> >     name: 'Nakatsukasa',
> >     fullName: 't2_2h1aa2w1',
> >     flairText: null,
> >     isBlocked: false,
> >     isPremium: false
> >   },
> >   post: {
> >     comments: 138,
> >     edited: false,
> >     imageURL: {
> >       url: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg',
> >       urlOverriden: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg'
> >     },
> >     score: 10541,
> >     thumbnail: {
> >       url: 'https://b.thumbs.redditmedia.com/Hp9GNib0kUhQ8UjO9CrXboOSYwBXOfGMWXLsQNNZ5_U.jpg',
> >       height: 140,
> >       width: 140
> >     },
> >     title: 'Now make him enter a cage match with Plato',
> >     votes: { up: 10541, upRatio: 0.99, Down: 0 },
> >     permaLink: 'https://www.reddit.com/r/HistoryMemes/comments/18kzxs9/now_make_him_enter_a_cage_match_with_plato/',
> >     extra: {
> >       archived: false,
> >       created: 1702872913,
> >       createdAsDate: 2023-12-18T04:15:13.000Z,
> >       isVideo: false,
> >       media_only: false,
> >       over18: false,
> >       pinned: false,
> >       spoiler: false
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There might be an issue on your end it's working correctly on mine..
> 
> I've modified the library a little, but I can't see where it would go wrong
> 
> ```js
> const https = require("https");
> 
> module.exports = class RedditMemesFetcher {
>     #API = `443:www.reddit.com:/r/{{Sub}}.json?sort=top&t=week`;
>     #REPO = "https://github.com/TheHellTower/Reddit-Meme-Fetcher"
>     #Format = ""; //ToDO: Add Format Support
> 
>     /**
>      * @constructor
>      * @param {string} Format json || description => (default: json = full data on the post.) (not implemented yet)
>      */
>     constructor(Format = "json") {
>         this.#Format = Format;
>     }
> 
>     /**
>      * Get A Random Meme
>      * @param {true} ageGate true || false => (default: true = filter +18 content)
>      * @returns {Promise<boolean>}
>      */
>     getRandomMeme(subreddit, ageGate = true) {
>         return new Promise(async (resolve, reject) => {
>             var splitted = this.#API.split(':');
>             var req = https.request({
>                 host: splitted[1],
>                 port: splitted[0],
>                 path: splitted[2].replace("{{Sub}}", subreddit),
>                 method: "GET",
>                 headers: {
>                     "User-Agent": this.#REPO
>                 }
>             }, res => {
>                 var jsonData = "";
> 
>                 res.on("data", body => {
>                     jsonData += body.toString();
>                 })
>                     .on("error", e => reject(e))
>                     .on("end", x => {
>                         jsonData = JSON.parse(jsonData);
>                         if (jsonData.error) return resolve({ error: true, data: { code: jsonData.error, message: jsonData.message } });
>                         const allowed = ageGate ? jsonData["data"]["children"].filter((post) => !post.data.over_18) : jsonData["data"]["children"];
>                         if (!allowed.length) return reject({ error: true, message: `There are no fresh \`${subreddit}\` memes try again !` });
>                         const randomMeme = allowed[Math.floor(Math.random() * allowed.length)];
>                         return resolve({
>                             error: false,
>                             data: {
>                                 sub: {
>                                     name: subreddit,
>                                     subscribers: randomMeme.data.subreddit_subscribers
>                                 },
>                                 author: {
>                                     name: randomMeme.data.author,
>                                     fullName: randomMeme.data.author_fullname,
>                                     flairText: randomMeme.data.author_flair_text,
>                                     isBlocked: randomMeme.data.author_is_blocked,
>                                     isPremium: randomMeme.data.author_premium
>                                 },
>                                 post: {
>                                     comments: randomMeme.data.num_comments,
>                                     edited: randomMeme.data.edited,
>                                     imageURL: {
>                                         url: randomMeme.data.url,
>                                         urlOverriden: randomMeme.data.url_overridden_by_dest
>                                     },
>                                     score: randomMeme.data.score,
>                                     thumbnail: {
>                                         url: randomMeme.data.thumbnail,
>                                         height: randomMeme.data.thumbnail_height,
>                                         width: randomMeme.data.thumbnail_width,
>                                     },
>                                     title: randomMeme.data.title,
>                                     votes: {
>                                         up: randomMeme.data.ups,
>                                         upRatio: randomMeme.data.upvote_ratio,
>                                         Down: randomMeme.data.downs
>                                     },
>                                     permaLink: `https://${splitted[1]}${randomMeme.data.permalink}`,
>                                     extra: {
>                                         archived: randomMeme.data.archived,
>                                         created: randomMeme.data.created,
>                                         createdAsDate: new Date(randomMeme.data.created * 1000),
>                                         isVideo: randomMeme.data.is_video,
>                                         media_only: randomMeme.data.media_only,
>                                         over18: randomMeme.data.over_18,
>                                         pinned: randomMeme.data.pinned,
>                                         spoiler: randomMeme.data.spoiler
>                                     }
>                                 }
>                             }
>                         });
>                     });
>             });
>             req.write(this.#REPO);
>             req.end();
>         });
>     }
> }
> ```

I don't know what you modified but need to read the whole to to know is kinda hell even if it's small, I believe you send too much requests :)

**Comment by iced-queen** [comment]
> > > > reddit-meme-fetcher@1.0.4 test
> > > > node test/Main.js
> > > 
> > > 
> > > ```js
> > > {
> > >   sub: { name: 'HistoryMemes', subscribers: 8817227 },
> > >   author: {
> > >     name: 'Nakatsukasa',
> > >     fullName: 't2_2h1aa2w1',
> > >     flairText: null,
> > >     isBlocked: false,
> > >     isPremium: false
> > >   },
> > >   post: {
> > >     comments: 138,
> > >     edited: false,
> > >     imageURL: {
> > >       url: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg',
> > >       urlOverriden: 'https://i.redd.it/2ni3cdbgbz6c1.jpeg'
> > >     },
> > >     score: 10541,
> > >     thumbnail: {
> > >       url: 'https://b.thumbs.redditmedia.com/Hp9GNib0kUhQ8UjO9CrXboOSYwBXOfGMWXLsQNNZ5_U.jpg',
> > >       height: 140,
> > >       width: 140
> > >     },
> > >     title: 'Now make him enter a cage match with Plato',
> > >     votes: { up: 10541, upRatio: 0.99, Down: 0 },
> > >     permaLink: 'https://www.reddit.com/r/HistoryMemes/comments/18kzxs9/now_make_him_enter_a_cage_match_with_plato/',
> > >     extra: {
> > >       archived: false,
> > >       created: 1702872913,
> > >       createdAsDate: 2023-12-18T04:15:13.000Z,
> > >       isVideo: false,
> > >       media_only: false,
> > >       over18: false,
> > >       pinned: false,
> > >       spoiler: false
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > There might be an issue on your end it's working correctly on mine..
> > 
> > 
> > I've modified the library a little, but I can't see where it would go wrong
> > ```js
> > const https = require("https");
> > 
> > module.exports = class RedditMemesFetcher {
> >     #API = `443:www.reddit.com:/r/{{Sub}}.json?sort=top&t=week`;
> >     #REPO = "https://github.com/TheHellTower/Reddit-Meme-Fetcher"
> >     #Format = ""; //ToDO: Add Format Support
> > 
> >     /**
> >      * @constructor
> >      * @param {string} Format json || description => (default: json = full data on the post.) (not implemented yet)
> >      */
> >     constructor(Format = "json") {
> >         this.#Format = Format;
> >     }
> > 
> >     /**
> >      * Get A Random Meme
> >      * @param {true} ageGate true || false => (default: true = filter +18 content)
> >      * @returns {Promise<boolean>}
> >      */
> >     getRandomMeme(subreddit, ageGate = true) {
> >         return new Promise(async (resolve, reject) => {
> >             var splitted = this.#API.split(':');
> >             var req = https.request({
> >                 host: splitted[1],
> >                 port: splitted[0],
> >                 path: splitted[2].replace("{{Sub}}", subreddit),
> >                 method: "GET",
> >                 headers: {
> >                     "User-Agent": this.#REPO
> >                 }
> >             }, res => {
> >                 var jsonData = "";
> > 
> >                 res.on("data", body => {
> >                     jsonData += body.toString();
> >                 })
> >                     .on("error", e => reject(e))
> >                     .on("end", x => {
> >                         jsonData = JSON.parse(jsonData);
> >                         if (jsonData.error) return resolve({ error: true, data: { code: jsonData.error, message: jsonData.message } });
> >                         const allowed = ageGate ? jsonData["data"]["children"].filter((post) => !post.data.over_18) : jsonData["data"]["children"];
> >                         if (!allowed.length) return reject({ error: true, message: `There are no fresh \`${subreddit}\` memes try again !` });
> >                         const randomMeme = allowed[Math.floor(Math.random() * allowed.length)];
> >                         return resolve({
> >                             error: false,
> >                             data: {
> >                                 sub: {
> >                                     name: subreddit,
> >                                     subscribers: randomMeme.data.subreddit_subscribers
> >                                 },
> >                                 author: {
> >                                     name: randomMeme.data.author,
> >                                     fullName: randomMeme.data.author_fullname,
> >                                     flairText: randomMeme.data.author_flair_text,
> >                                     isBlocked: randomMeme.data.author_is_blocked,
> >                                     isPremium: randomMeme.data.author_premium
> >                                 },
> >                                 post: {
> >                                     comments: randomMeme.data.num_comments,
> >                                     edited: randomMeme.data.edited,
> >                                     imageURL: {
> >                                         url: randomMeme.data.url,
> >                                         urlOverriden: randomMeme.data.url_overridden_by_dest
> >                                     },
> >                                     score: randomMeme.data.score,
> >                                     thumbnail: {
> >                                         url: randomMeme.data.thumbnail,
> >                                         height: randomMeme.data.thumbnail_height,
> >                                         width: randomMeme.data.thumbnail_width,
> >                                     },
> >                                     title: randomMeme.data.title,
> >                                     votes: {
> >                                         up: randomMeme.data.ups,
> >                                         upRatio: randomMeme.data.upvote_ratio,
> >                                         Down: randomMeme.data.downs
> >                                     },
> >                                     permaLink: `https://${splitted[1]}${randomMeme.data.permalink}`,
> >                                     extra: {
> >                                         archived: randomMeme.data.archived,
> >                                         created: randomMeme.data.created,
> >                                         createdAsDate: new Date(randomMeme.data.created * 1000),
> >                                         isVideo: randomMeme.data.is_video,
> >                                         media_only: randomMeme.data.media_only,
> >                                         over18: randomMeme.data.over_18,
> >                                         pinned: randomMeme.data.pinned,
> >                                         spoiler: randomMeme.data.spoiler
> >                                     }
> >                                 }
> >                             }
> >                         });
> >                     });
> >             });
> >             req.write(this.#REPO);
> >             req.end();
> >         });
> >     }
> > }
> > ```
> 
> I don't know what you modified but need to read the whole to to know is kinda hell even if it's small, I believe you send too much requests :)

I changed how I get the subreddit. Instead of using a random subreddit, I pass when calling the function. `getRandomMeme(subreddit, false)`.

I tried contacting Reddit through the link they provided in the page, then I'll let you know what they respond.

**Comment by iced-queen** [comment]
But something I'm confused about. https://github.com/reddit-archive/reddit/wiki/OAuth2:
Would I not need to pass in my  `secret` somewhere, and why do you pass in the repo as `User-Agent`? Don't know if any of those could have an effect, but worth mentioning. :)

**Comment by TheHellTower** [comment]
> But something I'm confused about. https://github.com/reddit-archive/reddit/wiki/OAuth2: Would I not need to pass in my `secret` somewhere, and why do you pass in the repo as `User-Agent`? Don't know if any of those could have an effect, but worth mentioning. :)

I don't know if it actually require a secret because on my side the actual code work.. And the User-Agent is not verified that's why I did that otherwise it would've had been a normal one haha

**Comment by iced-queen** [comment]
> > But something I'm confused about. https://github.com/reddit-archive/reddit/wiki/OAuth2: Would I not need to pass in my `secret` somewhere, and why do you pass in the repo as `User-Agent`? Don't know if any of those could have an effect, but worth mentioning. :)
> 
> I don't know if it actually require a secret because on my side the actual code work.. And the User-Agent is not verified that's why I did that otherwise it would've had been a normal one haha

Alright. I guess it's just my IP being blocked then, either for rate limiting or someone who used my bot to make dumb searches. Either way, I'll wait and see what Reddit says :)

**Comment by TheHellTower** [comment]
> > > But something I'm confused about. https://github.com/reddit-archive/reddit/wiki/OAuth2: Would I not need to pass in my `secret` somewhere, and why do you pass in the repo as `User-Agent`? Don't know if any of those could have an effect, but worth mentioning. :)
> > 
> > 
> > I don't know if it actually require a secret because on my side the actual code work.. And the User-Agent is not verified that's why I did that otherwise it would've had been a normal one haha
> 
> Alright. I guess it's just my IP being blocked then, either for rate limiting or someone who used my bot to make dumb searches. Either way, I'll wait and see what Reddit says :)

If you make a lot of requests they for sure limit you yeah !
Taking into account `Your request has been blocked due to a network policy.` on your page I believe you have been banned for a potential spam (`but I don't know the time so maybe temporary`)

**Comment by iced-queen** [comment]
> > > > But something I'm confused about. https://github.com/reddit-archive/reddit/wiki/OAuth2: Would I not need to pass in my `secret` somewhere, and why do you pass in the repo as `User-Agent`? Don't know if any of those could have an effect, but worth mentioning. :)
> > > 
> > > 
> > > I don't know if it actually require a secret because on my side the actual code work.. And the User-Agent is not verified that's why I did that otherwise it would've had been a normal one haha
> > 
> > 
> > Alright. I guess it's just my IP being blocked then, either for rate limiting or someone who used my bot to make dumb searches. Either way, I'll wait and see what Reddit says :)
> 
> If you make a lot of requests they for sure limit you yeah ! Taking into account `Your request has been blocked due to a network policy.` on your page I believe you have been banned for a potential spam (`but I don't know the time so maybe temporary`)

Well my bot is in 15K+ servers, with a total of 690K+ users. And there are much larger bots out there that also uses Reddit, so that'd be a massive flaw on Reddit's end in my opinion...

**Comment by TheHellTower** [comment]
> > > > > But something I'm confused about. https://github.com/reddit-archive/reddit/wiki/OAuth2: Would I not need to pass in my `secret` somewhere, and why do you pass in the repo as `User-Agent`? Don't know if any of those could have an effect, but worth mentioning. :)
> > > > 
> > > > 
> > > > I don't know if it actually require a secret because on my side the actual code work.. And the User-Agent is not verified that's why I did that otherwise it would've had been a normal one haha
> > > 
> > > 
> > > Alright. I guess it's just my IP being blocked then, either for rate limiting or someone who used my bot to make dumb searches. Either way, I'll wait and see what Reddit says :)
> > 
> > 
> > If you make a lot of requests they for sure limit you yeah ! Taking into account `Your request has been blocked due to a network policy.` on your page I believe you have been banned for a potential spam (`but I don't know the time so maybe temporary`)
> 
> Well my bot is in 15K+ servers, with a total of 690K+ users. And there are much larger bots out there that also uses Reddit, so that'd be a massive flaw on Reddit's end in my opinion...

I believe these bots are going through a paid thing or using proxies, I'm unable to find any doc about any secret or even any bot to create, do you have links for these so I can update the lib to add these possibilities ?

**Comment by TheHellTower** [comment]
> > > > > > > But something I'm confused about. https://github.com/reddit-archive/reddit/wiki/OAuth2: Would I not need to pass in my `secret` somewhere, and why do you pass in the repo as `User-Agent`? Don't know if any of those could have an effect, but worth mentioning. :)
> > > > > > 
> > > > > > 
> > > > > > I don't know if it actually require a secret because on my side the actual code work.. And the User-Agent is not verified that's why I did that otherwise it would've had been a normal one haha
> > > > > 
> > > > > 
> > > > > Alright. I guess it's just my IP being blocked then, either for rate limiting or someone who used my bot to make dumb searches. Either way, I'll wait and see what Reddit says :)
> > > > 
> > > > 
> > > > If you make a lot of requests they for sure limit you yeah ! Taking into account `Your request has been blocked due to a network policy.` on your page I believe you have been banned for a potential spam (`but I don't know the time so maybe temporary`)
> > > 
> > > 
> > > Well my bot is in 15K+ servers, with a total of 690K+ users. And there are much larger bots out there that also uses Reddit, so that'd be a massive flaw on Reddit's end in my opinion...
> > 
> > 
> > I believe these bots are going through a paid thing or using proxies, I'm unable to find any doc about any secret or even any bot to create, do you have links for these so I can update the lib to add these possibilities ?
> 
> I have no idea where the `secret` is used. I just saw it [here](https://old.reddit.com/prefs/apps/).

I can't find any documentation for it..

**Comment by iced-queen** [comment]
I just tried to run my bot on my local PC instead and everything worked on there, so it's definitely my VPS being IP blocked for some reason.
But thanks for your help anyway (and for this great library) 😄

**Comment by iced-queen** [comment]
Okay actually, I believe it's because my IP got flagged as an app, therefore requires `"Authorization" in the headers.

![img](https://i.gyazo.com/3b9d5b48b941bb192ed81844d0921166.png)
After adding this, it worked again.

**Comment by TheHellTower** [comment]
> I just tried to run my bot on my local PC instead and everything worked on there, so it's definitely my VPS being IP blocked for some reason. But thanks for your help anyway (and for this great library) 😄

Anyone can make such simple library so no reason to be thankful.. 🤷‍♂️

**Comment by TheHellTower** [comment]
> Okay actually, I believe it's because my IP got flagged as an app, therefore requires `"Authorization" in the headers.
> 
> ![img](https://camo.githubusercontent.com/49b9e8818029c6e739cabb20d0a743854e0c1f5a7a45484a933ad6d96e33f764/68747470733a2f2f692e6779617a6f2e636f6d2f33623964356234386239343162623139326564383138343464303932313136362e706e67) After adding this, it worked again.

I'll push a very small update in the week to let users pass an Authorization maybe it will solve the issue for a while ! :)

**Comment by TheHellTower** [comment]
https://github.com/TheHellTower/Reddit-Meme-Fetcher/commit/eea759902d2b98269aa46f7ea6efce2b3a9f5e85 add the ability to put an Authorization header.
Let me know if it solved your issue.

**Comment by iced-queen** [comment]
> [eea7599](https://github.com/TheHellTower/Reddit-Meme-Fetcher/commit/eea759902d2b98269aa46f7ea6efce2b3a9f5e85) add the ability to put an Authorization header. Let me know if it solved your issue.

Well yeah, adding the Authorization header fixes the issue and is apparently required if your IP is flagged as an app 😅 
So good thing that it's added 🙂 

Maybe add an error message in case this issue occurs for others so they don't just get a syntax error cause it returns an HTML page :3

**Comment by TheHellTower** [comment]
> > [eea7599](https://github.com/TheHellTower/Reddit-Meme-Fetcher/commit/eea759902d2b98269aa46f7ea6efce2b3a9f5e85) add the ability to put an Authorization header. Let me know if it solved your issue.
> 
> Well yeah, adding the Authorization header fixes the issue and is apparently required if your IP is flagged as an app 😅 So good thing that it's added 🙂
> 
> Maybe add an error message in case this issue occurs for others so they don't just get a syntax error cause it returns an HTML page :3

Well if an issue occur with authorization I don't know what the page would looks like so I will have to wait to see it !
I consider your actual issue as solved !

Fixed By https://github.com/TheHellTower/Reddit-Meme-Fetcher/commit/eea759902d2b98269aa46f7ea6efce2b3a9f5e85
